### PR TITLE
Added environment variables provider

### PR DESCRIPTION
**Pull request by shendrix**
Added a provider to pull from environment variables.

Also fixed a NPE with ProjectInfoProvider

### CODE REVIEW

**Comment by rodiontsev** [comment]
Thank you for your pull request!

I have cherry-picked the following commits and merged them into ```master```:
- [Added EnvironmentVariablesProvider](https://github.com/shendrix/maven-build-info-plugin/commit/bcc96dc0af158b765366f1109be423313c9da1bc)
- [Fixed NPE in ProjectInfoProvider when no project info elements present](https://github.com/shendrix/maven-build-info-plugin/commit/40ae4db5c3b78378d6be2ab8a79c8c447084f3f2)

With regard to [Updated pom version](https://github.com/shendrix/maven-build-info-plugin/commit/153cae6bec670f7b1d95511f76699d2efeb78469), I would like to create a release build (1.1) and deploy it into Maven Central rather then simply updating the version. I will let you know once I finish.

**Comment by shendrix** [comment]
Great! I didn't intend to include the pom update. Are you planning on release an update to Maven Central soon? Thanks

**Comment by rodiontsev** [comment]
I have released an update to Maven Central. Please note that the artifactId has been changed because of [Plugin Naming Convention](http://maven.apache.org/guides/plugin/guide-java-plugin-development.html#Plugin_Naming_Convention_and_Apache_Maven_Trademark).                 
```xml
<groupId>com.rodiontsev.maven.plugins</groupId>
<artifactId>build-info-maven-plugin</artifactId>
<version>1.1</version>
```

**Comment by shendrix** [comment]
Perfect, thank you!

**Pull request closed without merging**
